// Package declaration for the model class related to Customer
package com.vehicle_status_api.VehicleStatus.model;

//JPA entity mapping
import jakarta.persistence.*;

// The Customer class represents a customer entity that will be mapped to a database table
@Entity
public class Customer {

    // The id field is marked as the primary key and will be auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // ID is generated using the identity strategy
    private Long id;

    private String name;
    private String address;

    // Getter and setter methods

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getAddress() { return address; }
    public void setAddress(String address) { this.address = address; }
}